name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Tests
        run: npm test

      - name: Check types
        run: npm run types:check

      - name: Lint
        run: npm run lint

      - name: Check exports
        run: npm run exports:check

      - name: Build
        run: npm run build
